export const BASE_URL = 'https://banko.pythonanywhere.com/';

export const ENDPOINTS = {
  // ─── Auth & User ───
  BASE_URL,
  register: `${BASE_URL}auth/register`,
  login: `${BASE_URL}auth/login`,
  otp: `${BASE_URL}auth/otp`,
  verifyOtp: `${BASE_URL}auth/verify-otp`,
  resetPassword: `${BASE_URL}auth/reset-password`,
  dashboard: `${BASE_URL}user/dashboard`,
  transactionHistory: `${BASE_URL}user/history`,
  activeInvestments: `${BASE_URL}user/investments/active`,
  profits: `${BASE_URL}user/profits`,
  deposits: `${BASE_URL}user/deposits`,
  withdrawals: `${BASE_URL}user/withdrawals`,
  referrals: `${BASE_URL}user/referals`,
  paymentMethods: `${BASE_URL}super/payment-methods`,
  deposit: `${BASE_URL}user/deposit`,
  withdraw: `${BASE_URL}user/withdraw`,
  transfer: `${BASE_URL}user/transfer`,
  updateProfile: `${BASE_URL}user/profile/update`,
  withdrawalInfo: `${BASE_URL}user/profile/withdrawal`,
  createWithdrawalInfo: `${BASE_URL}user/profile/withdrawal/create`,
  otherSettings: `${BASE_URL}user/other-settings`,
  updateSettings: `${BASE_URL}user/settings/notifications`,
  changePassword: `${BASE_URL}auth/change-password`,
  plans: `${BASE_URL}super/plans`,
  createInvestment: `${BASE_URL}user/investments/create`,
  kycSubmit: `${BASE_URL}user/kyc/submit`,
  toggleAutoReinvest: (id: number | string) => `${BASE_URL}user/investment/${id}/toggle-auto-reinvest`,
  verifyAccount: (token: string) => `${BASE_URL}auth/verify/${token}`,

  // ─── Admin ───
  adminDashboard: `${BASE_URL}administrator/dashboard`,
  adminUsers: `${BASE_URL}administrator/users`,
  adminUser: (id: number | string) => `${BASE_URL}administrator/users/${id}`,
  adminPlans: `${BASE_URL}administrator/plans`,
  adminPlan: (id: number | string) => `${BASE_URL}administrator/plans/${id}`,
  adminActiveInvestments: `${BASE_URL}administrator/active-investments`,
  adminDeposits: `${BASE_URL}administrator/deposits`,
  adminApproveDeposit: (id: number | string) => `${BASE_URL}administrator/deposits/${id}/approve`,
  adminWithdrawals: `${BASE_URL}administrator/withdrawals`,
  adminApproveWithdrawal: (id: number | string) => `${BASE_URL}administrator/withdrawals/${id}/approve`,
  adminDeleteWithdrawal: (id: number | string) => `${BASE_URL}administrator/withdrawals/${id}/delete`,
  adminProfits: `${BASE_URL}administrator/profits`,
  adminBonuses: `${BASE_URL}administrator/bonuses`,
  adminCreateBonus: `${BASE_URL}administrator/bonuses/create`,
  adminPenalties: `${BASE_URL}administrator/penalties`,
  adminCreatePenalty: `${BASE_URL}administrator/penalties/create`,
  adminReferrals: `${BASE_URL}administrator/referrals`,
  adminReferralBonuses: `${BASE_URL}administrator/referral-bonuses`,
  adminKyc: `${BASE_URL}administrator/kyc`,
  adminKycApprove: (id: number | string) => `${BASE_URL}administrator/kyc/${id}`,
  adminPaymentMethods: `${BASE_URL}administrator/payment-methods`,
  adminCreatePaymentMethod: `${BASE_URL}administrator/payment-methods/create`,
  adminUpdatePaymentMethod: (id: number | string) => `${BASE_URL}administrator/payment-methods/${id}/update`,
  adminDeletePaymentMethod: (id: number | string) => `${BASE_URL}administrator/payment-methods/${id}/delete`,
  adminSettings: `${BASE_URL}administrator/settings`,
};
